[project]
name = "aura"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "google-generativeai>=0.8.5",
    "keybert>=0.9.0",
    "python-dotenv>=1.1.0",
    "torch>=2.7.0",
]
