from .summary import (
    SUMMARY_PROMPT,
    SUMMARY_SYS_PROMPT,
    COMPARISON_PROMPT,
    COMPARISON_SYS_PROMPT,
)

__all__ = [
    "SUMMARY_PROMPT",
    "SUMMARY_SYS_PROMPT",
    "COMPARISON_PROMPT",
    "COMPARISON_SYS_PROMPT",
]
